set_property PACKAGE_PIN AW31 [get_ports clk]	
create_clock -add -name sys_clk_pin -period 6.00 -waveform {0 3} [get_ports clk]

set_property PACKAGE_PIN AK13 [get_ports {dataout[0]}]	
set_property PACKAGE_PIN AK14 [get_ports {dataout[1]}]	
set_property PACKAGE_PIN AM12 [get_ports {dataout[2]}]	
set_property PACKAGE_PIN AM13 [get_ports {dataout[3]}]	
set_property PACKAGE_PIN AJ12 [get_ports {dataout[4]}]	
set_property PACKAGE_PIN AJ13 [get_ports {dataout[5]}]	
set_property PACKAGE_PIN AL12 [get_ports {dataout[6]}]	
set_property PACKAGE_PIN AK12 [get_ports {dataout[7]}]	
